# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_new_optimization_problem <- function(nrow = 1000000L, ncol = 1000000L, ncell = 100000L) {
    .Call(`_ppr_rcpp_new_optimization_problem`, nrow, ncol, ncell)
}

rcpp_predefined_optimization_problem <- function(l) {
    .Call(`_ppr_rcpp_predefined_optimization_problem`, l)
}

rcpp_optimization_problem_as_list <- function(x) {
    .Call(`_ppr_rcpp_optimization_problem_as_list`, x)
}

rcpp_get_optimization_problem_ncol <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_ncol`, x)
}

rcpp_get_optimization_problem_nrow <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_nrow`, x)
}

rcpp_get_optimization_problem_ncell <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_ncell`, x)
}

rcpp_get_optimization_problem_A <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_A`, x)
}

rcpp_get_optimization_problem_modelsense <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_modelsense`, x)
}

rcpp_get_optimization_problem_number_of_projects <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_number_of_projects`, x)
}

rcpp_get_optimization_problem_number_of_actions <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_number_of_actions`, x)
}

rcpp_get_optimization_problem_number_of_features <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_number_of_features`, x)
}

rcpp_get_optimization_problem_vtype <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_vtype`, x)
}

rcpp_get_optimization_problem_obj <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_obj`, x)
}

rcpp_get_optimization_problem_rhs <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_rhs`, x)
}

rcpp_get_optimization_problem_sense <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_sense`, x)
}

rcpp_get_optimization_problem_lb <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_lb`, x)
}

rcpp_get_optimization_problem_ub <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_ub`, x)
}

rcpp_get_optimization_problem_col_ids <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_col_ids`, x)
}

rcpp_get_optimization_problem_row_ids <- function(x) {
    .Call(`_ppr_rcpp_get_optimization_problem_row_ids`, x)
}

rcpp_branch_matrix <- function(x) {
    .Call(`_ppr_rcpp_branch_matrix`, x)
}

