# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_branch_matrix <- function(x) {
    .Call(`_ppr_rcpp_branch_matrix`, x)
}

